### ISSUE TITLE
Add ability to specify fetchOptions on fetch & push execution

### ISSUE THREAD

**Issue by andyrichardson** [andyrichardson/tipple#41]
#### Overview
There will inevitably be edge cases where a mutation needs to be triggered immediately following a state change.

> Note: Most of the time, this shouldn't be the case as state change events should ideally be separate from submission events.

This could be problematic as the change in state may not be applied until a later render.

#### Proposal
Add argument to executeRequest which allows fetchOptions to be specified.

Example button click handler
```tsx
const newVal = value + 10;

setValue(newVal) // Update state
executeRequest({ body: JSON.stringify(newVal) }); // Immediately make api call
```

**Comment by bogdansoare** [comment]
hey @andyrichardson 👋 , first of all thank you for this awesome lib, I've been playing around with it coming from graphql to a REST project and it's pretty nice.

This feature, to have the ability to pass options when executing an `usePush` would be awesome, for example imagine that you don't have access to the data when you call the `usePush` hook because it's stored in a form library like formik or final-form and you want to execute the push when you submit the form with provided values

**Comment by bogdansoare** [comment]
my bad, wasn't putting the `body` in the `fetchOptions` object, all good ❤️

**Comment by andyrichardson** [comment]
@bogdansoare no worries. Thanks for the kind feedback 🙏
